var threatdata = {
    "name": "Lurk",
    "alias": "Lurk",
    "category": "APT",
    "type": "-",
    "modified": "2020-04-14",
    "all_data": {
        "actor": "Lurk",
        "names": [
            {
                "name": "Lurk",
                "name-giver": "Kaspersky"
            }
        ],
        "country": [
            "Russia"
        ],
        "motivation": [
            "Financial crime"
        ],
        "first-seen": "2011",
        "description": "(Kaspersky) When we first encountered Lurk, in 2011, it was a nameless Trojan. It all started when we became aware of a number of incidents at several Russian banks that had resulted in the theft of large sums of money from customers. To steal the money, the unknown criminals used a hidden malicious program that was able to interact automatically with the financial institution\u2019s remote banking service (RBS) software; replacing bank details in payment orders generated by an accountant at the attacked organization, or even generating such orders by itself.\n\nIn 2016, it is hard to imagine banking software that does not demand some form of additional authentication, but things were different back in 2011. In most cases, the attackers only had to infect the computer on which the RBS software was installed in order to start stealing the cash. Russia\u2019s banking system, like those of many other countries, was unprepared for such attacks, and cybercriminals were quick to exploit the security gap.\n\nSo we decided to take a closer look at the malware. The first attempts to understand how the program worked gave our analysts nothing. Regardless of whether it was launched on a virtual or a real machine, it behaved in the same way: it didn\u2019t do anything. This is how the program, and later the group behind it, got its name. To \u201clurk\u201d means to hide, generally with the intention of ambush.\n\nWe were soon able to help investigate another incident involving Lurk. This time we got a chance to explore the image of the attacked computer. There, in addition to the familiar malicious program, we found a .dll file with which the main executable file could interact. This was our first piece of evidence that Lurk had a modular structure.\n\nLater discoveries suggest that, in 2011, Lurk was still at an early stage of development. It was formed of just two components, a number that would grow considerably over the coming years.",
        "observed-sectors": [
            "Financial",
            "Media"
        ],
        "observed-countries": [
            "Russia"
        ],
        "tools": [
            "Lurk"
        ],
        "counter-operations": [
            {
                "date": "2016-06",
                "activity": "Russia arrests 50, shuts down 5-year, $25m cyber bank robbery\nhttps://nakedsecurity.sophos.com/2016/06/06/russia-arrests-50-shuts-down-5-year-25m-cyber-bank-robbery/"
            }
        ],
        "information": [
            "https://securelist.com/the-hunt-for-lurk/75944/"
        ],
        "uuid": "20da2b77-e300-48ff-afb9-a997e6c0f297",
        "last-card-change": "2020-04-14",
        "source": "https://apt.etda.or.th/cgi-bin/listtools.cgi"
    },
    "ioc_data": [],
    "last_ioc_update": null,
    "file_name": "lurk",
    "analysis": null,
    "articles": [
        {
            "data_url": "https://www.secureworks.com/research/malware-analysis-of-the-lurk-downloader",
            "date": "2014-08-07",
            "organization": "Secureworks",
            "author": "Brett Stone-Gross",
            "title": "Malware Analysis of the Lurk Downloader",
            "categories": [
                "Lurk"
            ]
        }
    ],
    "mitre": []
};