var threatdata = {
    "name": "MagicWeb",
    "alias": "MagicWeb",
    "category": "Malware",
    "type": "Backdoor",
    "modified": "2022-09-12",
    "all_data": {
        "tool": "MagicWeb",
        "names": [
            {
                "name": "MagicWeb"
            }
        ],
        "description": "(Microsoft) MagicWeb goes beyond the collection capabilities of FoggyWeb by facilitating covert access directly. MagicWeb is a malicious DLL that allows manipulation of the claims passed in tokens generated by an Active Directory Federated Services (AD FS) server. It manipulates the user authentication certificates used for authentication, not the signing certificates used in attacks like Golden SAML.",
        "category": "Malware",
        "type": [
            "Backdoor"
        ],
        "information": [
            "https://www.microsoft.com/security/blog/2022/08/24/magicweb-nobeliums-post-compromise-trick-to-authenticate-as-anyone/"
        ],
        "uuid": "4785839c-bd5f-4eee-a4ad-d18415ac2300",
        "last-card-change": "2022-09-12",
        "source": "https://apt.etda.or.th/cgi-bin/listtools.cgi"
    },
    "ioc_data": [],
    "last_ioc_update": null,
    "file_name": "magicweb",
    "analysis": null,
    "articles": [],
    "mitre": []
};