var threatdata = {
    "name": "MobileOrder",
    "alias": "MobileOrder",
    "category": "Malware",
    "type": "Backdoor, Info stealer, Exfiltration, Downloader",
    "modified": "2023-06-22",
    "all_data": {
        "tool": "MobileOrder",
        "names": [
            {
                "name": "MobileOrder"
            }
        ],
        "description": "(Palo Alto) The malware uses the AMAP SDK to get accurate location of infected devices by GPS, mobile network (such as base stations), WiFi and other information. MobileOrder acts on instructions provided by its C2 server, which it communicates with over TCP port 3728. All C2 communications are encrypted with the AES algorithm using a key generated by computing five MD5 hashes starting with the key \u201c1qazxcvbnm\u201d, and adding a salt value of \u201c.)1/\u201d in each iteration.\n\nThe C2 server will respond to requests from MobileOrder with commands that the Trojan refers to as \u201corders\u201d. MobileOrder contains a command handler with functionality that provides a fairly robust set of commands, as seen in Table 6. The first byte of data provided by the C2 server is order number, which is followed by the encrypted data that needed to carry out the specific order.",
        "category": "Malware",
        "type": [
            "Backdoor",
            "Info stealer",
            "Exfiltration",
            "Downloader"
        ],
        "information": [
            "https://unit42.paloaltonetworks.com/scarlet-mimic-years-long-espionage-targets-minority-activists/"
        ],
        "mitre-attack": [
            "https://attack.mitre.org/software/S0079/"
        ],
        "malpedia": [
            "https://malpedia.caad.fkie.fraunhofer.de/details/apk.mobile_order"
        ],
        "alienvault-otx": [
            "https://otx.alienvault.com/browse/pulses?q=tag:MobileOrder"
        ],
        "uuid": "e1aa1dd5-eaa8-4bb6-91be-ba0d350827bc",
        "last-card-change": "2023-06-22",
        "source": "https://apt.etda.or.th/cgi-bin/listtools.cgi"
    },
    "ioc_data": [],
    "last_ioc_update": null,
    "mitre": [],
    "file_name": "mobileorder",
    "analysis": null
};