var threatdata = {
    "name": "SwiftSlicer",
    "alias": "SwiftSlicer, JaguarBlade",
    "category": "Malware",
    "type": "Wiper",
    "modified": "2023-06-22",
    "all_data": {
        "tool": "SwiftSlicer",
        "names": [
            {
                "name": "SwiftSlicer"
            },
            {
                "name": "JaguarBlade"
            }
        ],
        "description": "(ESET) SwiftSlicer is detected by ESET products as WinGo/KillFiles.C. The malware was written in Go, a highly versatile, cross-platform programming language.\n\nWhen it comes to SwiftSlicer\u2019s method of destruction, ESET researchers had this to say: \u201cOnce executed it deletes shadow copies, recursively overwrites files located in %CSIDL_SYSTEM%\\drivers, %CSIDL_SYSTEM_DRIVE%\\Windows\\NTDS and other non-system drives and then reboots computer. For overwriting it uses 4096 bytes length block filled with randomly generated byte\u201d.",
        "category": "Malware",
        "type": [
            "Wiper"
        ],
        "information": [
            "https://www.welivesecurity.com/2023/01/27/swiftslicer-new-destructive-wiper-malware-ukraine/"
        ],
        "malpedia": [
            "https://malpedia.caad.fkie.fraunhofer.de/details/win.swiftslicer"
        ],
        "uuid": "769d41bc-33d6-4026-9456-2047d30e0a83",
        "last-card-change": "2023-06-22",
        "source": "https://apt.etda.or.th/cgi-bin/listtools.cgi"
    },
    "ioc_data": [],
    "last_ioc_update": null,
    "file_name": "swiftslicer",
    "analysis": null,
    "articles": [
        {
            "data_url": "https://www.microsoft.com/en-us/security/business/security-insider/wp-content/uploads/2023/03/A-year-of-Russian-hybrid-warfare-in-Ukraine_MS-Threat-Intelligence-1.pdf",
            "date": "2023-03-15",
            "organization": "Microsoft",
            "author": "Microsoft Threat Intelligence",
            "title": "A year of Russian hybrid warfare in Ukraine",
            "categories": [
                "CaddyWiper",
                "DesertBlade",
                "DoubleZero",
                "HermeticWiper",
                "INDUSTROYER2",
                "IsaacWiper",
                "PartyTicket",
                "SwiftSlicer",
                "WhisperGate"
            ]
        },
        {
            "data_url": "https://twitter.com/ESETresearch/status/1618960022150729728",
            "date": "2023-01-27",
            "organization": "ESET Research",
            "author": "ESET Research",
            "title": "Tweets on SwiftSlicer",
            "categories": [
                "SwiftSlicer"
            ]
        },
        {
            "data_url": "https://www.welivesecurity.com/2023/01/27/swiftslicer-new-destructive-wiper-malware-ukraine/",
            "date": "2023-01-27",
            "organization": "ESET Research",
            "author": "ESET Research",
            "title": "SwiftSlicer: New destructive wiper malware strikes Ukraine",
            "categories": [
                "SwiftSlicer"
            ]
        }
    ],
    "mitre": []
};