var threatdata = {
    "name": "VenomKit",
    "alias": "VenomKit",
    "category": "Malware",
    "type": "Loader",
    "modified": "2020-07-10",
    "all_data": {
        "tool": "VenomKit",
        "names": [
            {
                "name": "VenomKit"
            }
        ],
        "description": "(Proofpoint) We use this name to describe documents generated by a builder purchased from the same seller as Taurus builder. Depending on the variant it may exploit CVE-2017-0199, CVE-2017-8570, CVE-2017-8759, CVE-2017-11882, CVE-2018-0802, and/or CVE-2018-8174. Notably, VenomKit often also uses the same CMSTP bypass as {{Taurus Loader}}.",
        "category": "Malware",
        "type": [
            "Loader"
        ],
        "information": [
            "https://www.proofpoint.com/us/threat-insight/post/fake-jobs-campaigns-delivering-moreeggs-backdoor-fake-job-offers",
            "https://quointelligence.eu/2018/11/golden-chickens-uncovering-a-malware-as-a-service-maas-provider-and-two-new-threat-actors-using/"
        ],
        "uuid": "7ba478cd-6fa7-44ad-a08d-1fb2a8604185",
        "last-card-change": "2020-07-10",
        "source": "https://apt.etda.or.th/cgi-bin/listtools.cgi"
    },
    "ioc_data": [],
    "last_ioc_update": null,
    "file_name": "venomkit",
    "analysis": null,
    "articles": [],
    "mitre": []
};