var threatdata = {
    "name": "WastedLocker",
    "alias": "WastedLocker",
    "category": "Malware",
    "type": "Ransomware, Big Game Hunting",
    "modified": "2022-12-30",
    "all_data": {
        "tool": "WastedLocker",
        "names": [
            {
                "name": "WastedLocker"
            }
        ],
        "description": "(Fox-IT) The new WastedLocker ransomware appeared in May 2020 (a technical description is included below). The ransomware name is derived from the filename it creates which includes an abbreviation of the victim\u2019s name and the string \u2018wasted\u2019. The abbreviation of the victim\u2019s name was also seen in {{BitPaymer}}, although a larger portion of the organisation name was used in BitPaymer and individual letters were sometimes replaced by similar looking numbers.\n\nTechnically, WastedLocker does not have much in common with BitPaymer, apart from the fact that it appears that victim specific elements are added using a specific builder rather than at compile time, which is similar to BitPaymer. Some similarities were also noted in the ransom note generated by the two pieces of malware. The first WastedLocker example we found contained the victim name as in BitPaymer ransom notes and also included both a protonmail.com and tutanota.com email address. Later versions also contained other Protonmail and Tutanota email domains, as well as Eclipso and Airmail email addresses. Interestingly the user parts of the email addresses listed in the ransom messages are numeric (usually 5 digit numbers) which is similar to the 6 to 12 digit numbers seen used by BitPaymer in 2018.",
        "category": "Malware",
        "type": [
            "Ransomware",
            "Big Game Hunting"
        ],
        "information": [
            "https://research.nccgroup.com/2020/06/23/wastedlocker-a-new-ransomware-variant-developed-by-the-evil-corp-group/",
            "https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/wastedlocker-ransomware-us",
            "https://blog.talosintelligence.com/2020/07/wastedlocker-emerges.html",
            "https://labs.sentinelone.com/wastedlocker-ransomware-abusing-ads-and-ntfs-file-attributes/",
            "https://blog.malwarebytes.com/threat-spotlight/2020/07/threat-spotlight-wastedlocker-customized-ransomware/",
            "https://unit42.paloaltonetworks.com/wastedlocker/",
            "https://securelist.com/wastedlocker-technical-analysis/97944/",
            "https://news.sophos.com/en-us/2020/08/04/wastedlocker-techniques-point-to-a-familiar-heritage/",
            "https://www.csoonline.com/article/3574907/wastedlocker-explained-how-this-targeted-ransomware-extorts-millions-from-victims.html"
        ],
        "mitre-attack": [
            "https://attack.mitre.org/software/S0612/"
        ],
        "malpedia": [
            "https://malpedia.caad.fkie.fraunhofer.de/details/win.wastedlocker"
        ],
        "playbook": [
            "https://pan-unit42.github.io/playbook_viewer/?pb=wastedlocker-ransomware"
        ],
        "uuid": "d718aaef-4608-46fd-8245-a6036ebf54f2",
        "last-card-change": "2022-12-30",
        "source": "https://apt.etda.or.th/cgi-bin/listtools.cgi"
    },
    "analysis": {
        "id": "report--7596f10d-e0f7-4a9c-b7e3-b76e2ea3a476",
        "pb_file": "wastedlocker-ransomware.json",
        "last_updated": "2021-09-30T00:00:00.000Z",
        "title": "WASTEDLOCKER RANSOMWARE",
        "industries": [
            "energy",
            "engineering",
            "financial-services",
            "healthcare",
            "manufacturing",
            "pharmaceuticals",
            "retail",
            "technology",
            "transportation"
        ],
        "regions": [
            "US"
        ],
        "malwares": [
            "SocGholish",
            "WastedLocker"
        ]
    },
    "ioc_data": [
        {
            "malware_printable": "WastedLocker",
            "malware_alias": null,
            "malware": "win.wastedlocker",
            "last_update": "2021-04-06 13:14:40",
            "tags": [
                "wastedlocker"
            ],
            "ioc": {
                "sha256_hash": [
                    {
                        "value": "2261dbc9977932cd8dac9bccd7aae8472cdbd8e588aa4f10b02c8a1c0a6051d1",
                        "timestamp": "2021-04-06 13:14:40"
                    },
                    {
                        "value": "905ea119ad8d3e54cd228c458a1b5681abc1f35df782977a23812ec4efa0288a",
                        "timestamp": "2021-04-06 13:14:40"
                    }
                ],
                "md5_hash": [
                    {
                        "value": "82D841869E912A772413BB37F30307B0",
                        "timestamp": "2021-03-14 23:55:21"
                    }
                ]
            }
        }
    ],
    "last_ioc_update": "2021-04-06 13:14:40",
    "mitre": [],
    "file_name": "wastedlocker"
};