var threatdata = {
    "name": "Zeus",
    "alias": "Zeus, ZeuS, Zbot, Trojan.Zbot, Wsnpoem, Gorhax, Kneber",
    "category": "Malware",
    "type": "Banking trojan, Info stealer, Credential stealer, Downloader, Botnet",
    "modified": "2021-08-09",
    "all_data": {
        "tool": "Zeus",
        "names": [
            {
                "name": "Zeus"
            },
            {
                "name": "ZeuS"
            },
            {
                "name": "Zbot"
            },
            {
                "name": "Trojan.Zbot"
            },
            {
                "name": "Wsnpoem"
            },
            {
                "name": "Gorhax"
            },
            {
                "name": "Kneber"
            }
        ],
        "description": "(Talos) One of the most high-profile pieces of malware in the current threat landscape is Zeus/Zbot, a nasty little trojan that has been employed by botnet operators around the world to steal banking credentials and other personal data, participate in click-fraud schemes, and likely numerous other criminal enterprises. It is the engine behind notorious botnets such as Kneber, which has recently made headlines worldwide. The following is an analysis of the network traffic generated by machines that Talos intentionally infected with known Zeus samples, in order to study post-infection behavior. The machines were all base installations of Windows XP, Service Pack 2, with no patches - i.e., designed to be as vulnerable as possible.",
        "category": "Malware",
        "type": [
            "Banking trojan",
            "Info stealer",
            "Credential stealer",
            "Downloader",
            "Botnet"
        ],
        "information": [
            "https://talosintelligence.com/zeus_trojan",
            "https://usa.kaspersky.com/resource-center/threats/zeus-virus",
            "http://malwareint.blogspot.com/2010/02/facebook-phishing-campaign-proposed-by.html",
            "http://malwareint.blogspot.com/2010/02/zeus-on-irs-scam-remains-actively.html",
            "http://eternal-todo.com/blog/new-zeus-binary",
            "https://nakedsecurity.sophos.com/2010/07/24/sample-run/",
            "https://www.mnin.org/write/ZeusMalware.pdf",
            "http://malwareint.blogspot.com/2010/01/leveraging-zeus-to-send-spam-through.html",
            "http://eternal-todo.com/blog/zeus-spreading-facebook",
            "http://malwareint.blogspot.com/2010/03/new-phishing-campaign-against-facebook.html",
            "http://eternal-todo.com/blog/detecting-zeus",
            "https://www.secureworks.com/research/zeus?threat=zeus",
            "http://malwareint.blogspot.com/2009/07/special-zeus-botnet-for-dummies.html",
            "https://en.wikipedia.org/wiki/Zeus_(malware)",
            "https://blog.malwarebytes.com/101/2021/07/the-life-and-death-of-the-zeus-trojan/"
        ],
        "malpedia": [
            "https://malpedia.caad.fkie.fraunhofer.de/details/win.zeus"
        ],
        "uuid": "f186f5ea-0a67-47ff-affc-41f34e62725e",
        "last-card-change": "2021-08-09",
        "source": "https://apt.etda.or.th/cgi-bin/listtools.cgi"
    },
    "ioc_data": [
        {
            "malware_printable": "Zeus",
            "malware_alias": "Zbot",
            "malware": "win.zeus",
            "last_update": "2021-10-07 10:27:34",
            "tags": [
                "zeus",
                "Zeus"
            ],
            "ioc": {
                "sha1_hash": [
                    {
                        "value": "f375401470491a8f56b2ceb26b6a1d3ea84d8bd3",
                        "timestamp": "2021-10-07 10:27:34"
                    },
                    {
                        "value": "1c1596effa695ca855a914eb5caa9ff479d149e6",
                        "timestamp": "2021-09-13 09:11:23"
                    },
                    {
                        "value": "44749f36afabe3b8785914be193cdb0e44196c54",
                        "timestamp": "2021-09-13 09:04:11"
                    }
                ],
                "sha3_384_hash": [
                    {
                        "value": "beb6b598121ac19fb2465b147c1eb373d707e2a395ed0d2f871fdacfda82547cc3f15251c1113dc0c924cbc189193b2b",
                        "timestamp": "2021-10-07 10:27:14"
                    },
                    {
                        "value": "791f9f79459d1ab4910b1013cc2c3844af26641a6aa9695085d1dce7f25f9740e853803158b4b8cbf4267697daacdfc7",
                        "timestamp": "2021-09-13 09:10:56"
                    },
                    {
                        "value": "255c7a5603bb18b9351efa42324f071e78e8303a0258875b48f0e5bce5f740a237b11cdda80c056ae9fa14e1a1d29b32",
                        "timestamp": "2021-09-13 09:04:40"
                    }
                ],
                "md5_hash": [
                    {
                        "value": "ea30c0dc58f71a1720990021fda92d1e",
                        "timestamp": "2021-10-07 10:26:54"
                    },
                    {
                        "value": "5aff39b9d705974f87f58b420416b5fc",
                        "timestamp": "2021-09-13 09:10:10"
                    },
                    {
                        "value": "a6f3e35760bc2848cd258b786c1fd247",
                        "timestamp": "2021-09-13 09:03:37"
                    }
                ],
                "sha256_hash": [
                    {
                        "value": "a6512b5271bc6e383ec6e3141ebb91b92a8a76a5f1d532ee6e185a253dc20830",
                        "timestamp": "2021-10-07 10:26:31"
                    },
                    {
                        "value": "26cf98ecf5aded7945370a870d158447895b2bdd2a4b1e34c082130e4119be44",
                        "timestamp": "2021-09-13 09:10:34"
                    },
                    {
                        "value": "043f535f68678652c50ff49cf03ee4b63fdbd03b76c732adfe83074335fbbb3b",
                        "timestamp": "2021-09-13 09:05:25"
                    }
                ]
            }
        }
    ],
    "last_ioc_update": "2021-10-07 10:27:34",
    "mitre": [],
    "file_name": "zeus",
    "analysis": null
};