const rule = {
    "id": "5f211929-6b10-47b1-888d-29bf83c34e7a",
    "info": {
        "name": "Rules Detect Grandoreiro",
        "author": "Openhunting",
        "date": "2023-01-13",
        "modified": "2023-06-19 12:27:15",
        "severity": "High",
        "category": "Malware",
        "description": "Rules IOC for Grandoreiro",
        "tags": [
            "brazil",
            "banker",
            "Grandoreiro",
            "BRA",
            "ViriBack",
            "geo",
            "LatentBot"
        ],
        "references": []
    },
    "method": [
        {
            "query": "SELECT * FROM files_information",
            "column_master": "path",
            "signature": [
                {
                    "name": "hash",
                    "indicator": [
                        "62b4caf7036c0d416e660c3a693ce7eb47e82d4330786ecd833631d5f38b4a9a",
                        "9b976aba7e845b4741472a0bd39094e65ee4010d303974daee55c67568721427",
                        "a16c5b5e9d59ae6a194ed138e709d1e0f931bb1b3f6525e4b8c227711cb7c46d"
                    ]
                }
            ]
        },
        {
            "query": "select * from process_open_sockets",
            "column_master": "remote_access",
            "signature": [
                {
                    "name": "domain",
                    "indicator": [
                        "bwagi.daviluccadapaz.cfd",
                        "wraa2d.guilhermeduarte.xyz",
                        "t4ouer.davilucasmoreira.xyz",
                        "65iov4.luizotaviomoraes.mom",
                        "bjvjtmfgrettpckpf.collegefan.org",
                        "9ja9k.rafaeldarosa.xyz",
                        "wata.daviluccadapaz.cfd",
                        "a8eekt.davialmeida.pics",
                        "r9ou7j.ryandacunha.pics",
                        "nwadi.rafaeldarosa.xyz",
                        "pyaivm.davilucassilveira.mom",
                        "eta5f.davizuccapires.cfd",
                        "u2iifr.guilhermeduarte.xyz",
                        "puaejd.enzogabrielpereira.xyz",
                        "djuuup.daviluccadapaz.cfd",
                        "gojojomjwemjajoag.myeffect.net",
                        "e7oexr.vitorhugodaluz.pics",
                        "wa91.thomassilveira.cfd",
                        "u5oaer.thomassilveira.cfd",
                        "6suaer.ryandacunha.pics",
                        "cmii1s.rodrigomonteiro.one",
                        "wat3.davilucasmoreira.xyz",
                        "15.228.233.242",
                        "c8n5v0m1-y8c29n5-t73n919.s3.amazonaws.com",
                        "c4eiw7.thomassilveira.cfd",
                        "waa9.guilhermeduarte.xyz",
                        "5foaer.lorenzocardoso.cfd",
                        "wat8.enzogabrielpereira.xyz",
                        "wteoyh.davilucassilveira.mom",
                        "yneia4.davizuccapires.cfd",
                        "96iit4.vitorhugodaluz.pics",
                        "hjmretmcbbhtpckpf.collegefan.org",
                        "fjaer.davilucasmoreira.xyz",
                        "dwaeqf.pauloramos.mom",
                        "nfeconsumidor.s3.ir-thr-at1.arvanstorage.ir",
                        "0fuuyo.enzogabrielpereira.xyz",
                        "r6uedr.joaomiguelcunha.one",
                        "rtaefe.joaomiguelcunha.one",
                        "dguaiu.lorenzocardoso.cfd",
                        "ljemebcsmckbaaqag.ditchyourip.com",
                        "37eiwb.thomassilveira.cfd",
                        "wa37.luizotaviomoraes.mom",
                        "fvaaee.davialmeida.pics",
                        "nfefaturada19042023.s3.ir-thr-at1.arvanstorage.ir",
                        "4daaer.emanuellopes.one",
                        "restauranterota152.brazilsouth.cloudapp.azure.com",
                        "15.228.57.146",
                        "wea36.davialmeida.pics",
                        "5haiwe.emanuellopes.one",
                        "49uubr.davilucasmoreira.xyz",
                        "t8io7f.lorenzocardoso.cfd",
                        "wata.davizuccapires.cfd",
                        "jtvkerimftpckpf.dvrdns.org",
                        "bkcjtkgckvgtpckpf.collegefan.org",
                        "vmaee.noahdaconceicao.mom",
                        "sgbmebgakasbaaqag.ditchyourip.com",
                        "4kaaer.lorenzocardoso.cfd",
                        "fac-conectorfiscal.servebeer.com",
                        "15.229.47.198",
                        "nhaee.noahdaconceicao.mom",
                        "niuajc.vitorhugodaluz.pics",
                        "ggamebecababaaqag.ditchyourip.com",
                        "51oocm.davialmeida.pics",
                        "yniusj.pauloramos.mom",
                        "39eikc.rodrigomonteiro.one",
                        "wiwi.from-wi.com",
                        "raipb.emanuellopes.one",
                        "miousj.davilucassilveira.mom",
                        "jbawr.rafaeldarosa.xyz",
                        "4yiu7f.pauloramos.mom",
                        "waea.kaiquenascimento.one",
                        "mbawr.luizotaviomoraes.mom",
                        "192.95.6.196",
                        "a8eiwb.ryandacunha.pics",
                        "185.191.228.227",
                        "dkawt.joaomiguelcunha.one",
                        "172.96.137.108",
                        "wea82.kaiquenascimento.one",
                        "51.77.193.20",
                        "96iirn.daviluccadapaz.cfd",
                        "waa7.thomassilveira.cfd",
                        "dkaew.rafaeldarosa.xyz",
                        "95iir4.emanuellopes.one",
                        "topgearagainsix.uksouth.cloudapp.azure.com",
                        "hwajp.davilucassilveira.mom",
                        "18.231.154.55",
                        "beai3f.rodrigomonteiro.one",
                        "wat3.pauloramos.mom",
                        "hcaee6.davizuccapires.cfd",
                        "p1iocr.luizotaviomoraes.mom",
                        "lwat8.guilhermeduarte.xyz",
                        "w6oacr.fernandocosta.pics",
                        "ewaes8.ryandacunha.pics",
                        "bbagmkabgbaaqag.dyndns-remote.com",
                        "mfpretejcvptpckpf.collegefan.org",
                        "lz-v2.dynalias.com",
                        "ximbocadaparafuseta.com",
                        "nooar2.rodrigomonteiro.one",
                        "pha3j.noahdaconceicao.mom",
                        "h4ii2d.fernandocosta.pics",
                        "waet.kaiquenascimento.one",
                        "acqgbbmsmebbaaqag.ditchyourip.com",
                        "kqagbqsaqbsbaaqag.ditchyourip.com",
                        "wart.fernandocosta.pics",
                        "wsueew.fernandocosta.pics",
                        "gbzqemkbmbaaqag.dyndns-remote.com",
                        "0guuua.vitorhugodaluz.pics",
                        "wea86.joaomiguelcunha.one",
                        "9haier.kaiquenascimento.one",
                        "eoiar6.noahdaconceicao.mom"
                    ]
                }
            ]
        }
    ]
};