const rule = {
    "id": "ad2408e9-fce1-4bad-8282-2eb27e7d1bfb",
    "info": {
        "name": "Rules Detect Bisonal",
        "author": "Openhunting",
        "date": "2022-07-07",
        "modified": "2023-09-20 07:36:22",
        "severity": "High",
        "category": "Malware",
        "description": "Rules IOC for Bisonal",
        "tags": [
            "APT",
            "TAG-74"
        ],
        "references": []
    },
    "method": [
        {
            "query": "select * from process_open_sockets",
            "column_master": "remote_access",
            "signature": [
                {
                    "name": "domain",
                    "indicator": [
                        "kybook.viewdns.net",
                        "leader.gotdns.ch",
                        "likms.hopto.org",
                        "logindaums.ddnsking.com",
                        "loginsdaum.viewdns.net",
                        "mafolog.serveminecraft.net",
                        "mailplug.ddnsking.com",
                        "minjoo2.servehttp.com",
                        "mintaek.bounceme.net",
                        "munjanara.servehttp.com",
                        "pattern.webhop.me",
                        "necgo.serveblog.net",
                        "pixoneer.myvnc.com",
                        "plomacy.ddnsking.com",
                        "proeso.servehttp.com",
                        "prparty.webhop.me",
                        "puacgo1.servemp3.com",
                        "saevit.servebeer.com",
                        "safety.viewdns.net",
                        "samgiblue.servegame.com",
                        "sarang.serveminecraft.net",
                        "satreci.bounceme.net",
                        "sejonglog.hopto.org",
                        "signga.redirectme.net",
                        "skparty.myonlineportal.org",
                        "steering.viewdns.net",
                        "stjpmsko.serveblog.net",
                        "themiujoo.viewdns.net",
                        "surveymonkey.myddns.me",
                        "tsuago.servehalflife.com",
                        "tsuagos.servehalflife.com",
                        "unipedu.servebeer.com",
                        "visdpaka.servemp3.com",
                        "visual.webhop.me",
                        "wwl1764.ddnsking.com",
                        "anrnet.servegame.com",
                        "alleyk.onthewifi.com",
                        "asheepa.sytes.net",
                        "attachdaum.servecounterstrike.com",
                        "attachmaildaum.serveblog.net",
                        "attachmaildaum.servecounterstrike.com",
                        "bizmeka.viewdns.net",
                        "bucketnec.bounceme.net",
                        "eduin21.zapto.org",
                        "chsoun.serveftp.com",
                        "ckstar.zapto.org",
                        "daecheol.myvnc.com",
                        "eburim.viewdns.net",
                        "elecinfonec.servehalflife.com",
                        "foodlab.hopto.org",
                        "finance.my-homeip.com",
                        "formsgle.freedynamicdns.net",
                        "formsgle.freedynamicdns.org",
                        "fresh.servepics.com",
                        "global.freedynamicdns.net",
                        "global.freedynamicdns.org",
                        "hairouni.serveblog.net",
                        "hamonsoft.serveblog.net",
                        "hanseo1.hopto.org",
                        "harvest.my-homeip.net",
                        "hometax.onthewifi.com",
                        "hwarang.myddns.me",
                        "jaminss.viewdns.net",
                        "janara.freedynamicdns.org",
                        "jeoash.servemp3.com",
                        "jstreco.myftp.biz",
                        "kanager.bounceme.net",
                        "kcgselect.servehalflife.com",
                        "kjmacgk.ddnsking.com",
                        "kookmina.servecounterstrike.com",
                        "ksd22.myddns.me",
                        "kumohhic.viewdns.net"
                    ]
                }
            ]
        }
    ]
};